### ISSUE TITLE
DNS SRV record not registered in terraform state file

### ISSUE THREAD

**Issue by gerardbonneto** [scaleway/terraform-provider-scaleway#1064] opened 2022-01-31 12:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.15.1

### Affected Resource(s)

* scaleway_domain_record

### Terraform Configuration Files

```hcl
# Copy-paste the minimal (if possible) terraform configuration to reproduce the bug here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

```
  # scaleway_domain_record.proxy_srv["elb1"] will be created
  + resource "scaleway_domain_record" "proxy_srv" {
      + data            = "100 1 3128 elb1.preproduction"
      + dns_zone        = "exemple.xyz"
      + id              = (known after apply)
      + keep_empty_zone = false
      + name            = "_proxy-preproduction._tcp"
      + priority        = 0
      + project_id      = (known after apply)
      + ttl             = 60
      + type            = "SRV"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "preproduction"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

scaleway_domain_record.proxy_srv["elb1"]: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to scaleway_domain_record.proxy_srv["elb1"], provider "provider[\"registry.terraform.io/scaleway/scaleway\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behavior
An SRV entry is created within the domain root
Terraform state file (.tfsate) is updated with a block  of type": "scaleway_domain_record"
The SRV domain is reachable

### Actual Behavior
An SRV entry is created within the domain root
No  block  of type": "scaleway_domain_record" in .fstate
The SRV domain is reachable

### Steps to Reproduce
![Logo-Scaleway](https://user-images.githubusercontent.com/47356605/151790545-1cd4635b-1252-4ffb-9637-5aa88dd02026.svg)

1. `terraform apply`

### References

* #0000

**Comment by remyleone** [comment] 2022-01-31 17:05
Hello 👋  could you try to upgrade your terraform version and confirm that you are using the latest provider version?

**Comment by remyleone** [comment] 2022-05-06 16:24
I reproduce a problem with the following code:

```hcl
terraform {
  required_providers {
    scaleway = {
      source  = "scaleway/scaleway"
      version = "2.2.1-rc.3"
    }
  }
}

provider "scaleway" {
}

resource "scaleway_domain_record" "proxy_srv" {
  data            = "100 1 3128 elb1.preproduction"
  dns_zone        = "<TEST ZONE>"
  //keep_empty_zone = false
  name            = "_proxy-preproduction._tcp"
  priority        = 0
  ttl             = 60
  type            = "SRV"
}
```

```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to scaleway_domain_record.proxy_srv, provider "provider[\"registry.terraform.io/scaleway/scaleway\"]" produced an unexpected new value: Root
│ resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

**Comment by Monitob** [comment] 2022-09-15 15:42
I'm going to close this issue because it was already corrected and I'm unavailable to reproduce it again.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.

**Closed** 2022-09-16 13:09 UTC
Labels: bug, domain
