### ISSUE TITLE
​An error occurs if the ssh key needs to be destroyed and then created

### ISSUE THREAD

**Issue by smorimoto** [scaleway/terraform-provider-scaleway#713] opened 2020-11-22 17:06 UTC
I understand that this is an edge-case error, but it happens if the id changes.

For example, if you import all the keys from multiple GitHub users with the following code, you will most likely get that error:

https://github.com/actions-ml/infrastructure/blob/4ca166159e0e50b922e8c0b62ca4bc608a86d390/terraform/scaleway/ssh_keys.tf

```
Error: scaleway-sdk-go: http error 409 Conflict: conflict
```

**Comment by remyleone** [comment] 2020-11-22 19:41
This error happens because two keys are the same. Are you sure those keys are all unique?

**Comment by smorimoto** [comment] 2020-11-23 09:25
If you meant the ​`public_key`, yes, old and new one are the same. ​However, if the local name changes and the resource needs to be re-created, it should be deleted and re-added, not replaced.

**Comment by remyleone** [comment] 2020-11-23 15:16
I cannot reproduce with the following code:

```hcl
terraform {
  required_providers {
    scaleway = {
      source  = "scaleway/scaleway"
      version = "1.17.2"
    }
  }
}

provider "scaleway" {
  zone            = "fr-par-1"
  region          = "fr-par"
}

locals {
  github_usernames = [
    "remyleone",
  ]
}

data "http" "github_keys" {
  for_each = toset(local.github_usernames)

  url = format("https://github.com/%s.keys", each.key)
}

resource "scaleway_account_ssh_key" "ssh_keys" {
  for_each = { for idx, i in flatten([for username in local.github_usernames :
    [for idx, _line in
      compact(split("\n", data.http.github_keys[username].body)) :
      {
        name = username
        public_key = element(
          compact(split("\n", data.http.github_keys[username].body)),
          idx
        )
      }
  ]]) : format("%s.%d", i.name, idx) => i }

  name       = each.value.name
  public_key = each.value.public_key
}
```

If after a provider update, this bug continues to occur, feel free to open a new issue with the exact steps to reproduce the issue.

**Comment by smorimoto** [comment] 2020-11-23 15:21
For example, after you have created the resource, try to change `ssh_keys` to `ssh_keys1` and then apply. ​The error I'm talking about occurs in that case.

**Comment by smorimoto** [comment] 2020-11-23 15:22
The local name means here.

```diff
- resource "scaleway_account_ssh_key" "ssh_keys" {
+ resource "scaleway_account_ssh_key" "ssh_keys1" {
```

**Comment by remyleone** [comment] 2020-11-23 15:37
I get a destroy and recreate plan after I apply the change:

```
$ terraform apply
data.http.github_keys["remyleone"]: Refreshing state... [id=https://github.com/remyleone.keys]
scaleway_account_ssh_key.ssh_keys["remyleone.0"]: Refreshing state... [id=56f41850-b0b9-453f-a3f0-b5c6d29543f8]
scaleway_account_ssh_key.ssh_keys["remyleone.1"]: Refreshing state... [id=d957cb31-2a7f-4b68-9363-b128184b3c85]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # scaleway_account_ssh_key.ssh_keys["remyleone.0"] will be destroyed
  - resource "scaleway_account_ssh_key" "ssh_keys" {
      - id              = "56f41850-b0b9-453f-a3f0-b5c6d29543f8" -> null
      - name            = "remyleone" -> null
      - organization_id = "951df375-e094-4d26-97c1-ba548eeb9c42" -> null
      - public_key      = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9AjqOMo8AH25opNan2EkJA4/cGj5OU+r/ItNDsgKnDEpCG3Vatjbgw/d+KDI11hxqHWzASWFKOufDBqRpFk7f1ptZcuS0FdXY8Y5zWgfRo2ZYBjgrTtlwQdRfn1i94AQIo8P3pyYjZMWbGGmSpKPzpuHvWHCcdiGnftaaa31tuWsSnClCMJOge2AdVxv2b/vR0xaL0AdG1fHTQuhIsyaVriwImegXlssOA+01Hu7bil8c7QCN/xyVzlokVwJQLGTHHq/dIKRIH1irgU+GH7TBV2jdoz8Vv6U/uODio9BFYHFJaYYt3vGwRD5PmgDPunUiPKz08jYaimeSiBVlBMyT" -> null
    }

  # scaleway_account_ssh_key.ssh_keys["remyleone.1"] will be destroyed
  - resource "scaleway_account_ssh_key" "ssh_keys" {
      - id              = "d957cb31-2a7f-4b68-9363-b128184b3c85" -> null
      - name            = "remyleone" -> null
      - organization_id = "951df375-e094-4d26-97c1-ba548eeb9c42" -> null
      - public_key      = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDZrUk+hFs8hYZVu6PVzXIZH83glJfiqZU7gzxw9zSkinCNHZnJ0KViZmol/XUEvGPu0toWOnM5t9MUVRq3xMldo6TKOZ7tvqBDoYD/hMHSBZb+b5f12l7i43wV7dunypy+nKtlb+rv9YJdMdbVaXy29K5EPaQujYTZTvXFEB9b8P0NXt0jA+qsUEf6/TK7dONdh2PFrUFiLXtNxkw21n/q6JGfR78etQ3mIaDKffjoVYHKgMv2edGWpjAkZeM5eBg6U6kb7CMMstpxPfOPADkXu4hbWhMGG5TC4tuizfq8YAeE8t2nyfB+xq8MtQe5jTPLK1/B+NVuKvp+3WLDSrai6dbsMpFsZDXJL34BkoY7XsRf8FeaPiy5Z3ScD6YLTl986rztAPyLCKJrfPSSc2tAOgne9cGFVUPS+tehqtW+VPeD4qu00h7H9hX/x+hefqYL5cfS3h/qgpcUFw+69rVK6r1zcBwJyJAI9gUQ08628iirYku3KkUQ0VdlavrYYfB9wyStQ4VBUYpXKMhKgk5gCRRkEuJ2gETffj+nLZAqL13yFPm8lCOgRztp06S+K9Xq/cYVvAnDh8R2IsBGbs4KmpKMM7PA7mYf3XMI1KzAWXqc6RCv1a+PUwMK/AIKqnk040n2Q0yxuJSOufcVE6mWxVywHag9Ucww1FuSR54i7w==" -> null
    }

  # scaleway_account_ssh_key.ssh_keys1["remyleone.0"] will be created
  + resource "scaleway_account_ssh_key" "ssh_keys1" {
      + id              = (known after apply)
      + name            = "remyleone"
      + organization_id = (known after apply)
      + public_key      = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9AjqOMo8AH25opNan2EkJA4/cGj5OU+r/ItNDsgKnDEpCG3Vatjbgw/d+KDI11hxqHWzASWFKOufDBqRpFk7f1ptZcuS0FdXY8Y5zWgfRo2ZYBjgrTtlwQdRfn1i94AQIo8P3pyYjZMWbGGmSpKPzpuHvWHCcdiGnftaaa31tuWsSnClCMJOge2AdVxv2b/vR0xaL0AdG1fHTQuhIsyaVriwImegXlssOA+01Hu7bil8c7QCN/xyVzlokVwJQLGTHHq/dIKRIH1irgU+GH7TBV2jdoz8Vv6U/uODio9BFYHFJaYYt3vGwRD5PmgDPunUiPKz08jYaimeSiBVlBMyT"
    }

  # scaleway_account_ssh_key.ssh_keys1["remyleone.1"] will be created
  + resource "scaleway_account_ssh_key" "ssh_keys1" {
      + id              = (known after apply)
      + name            = "remyleone"
      + organization_id = (known after apply)
      + public_key      = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDZrUk+hFs8hYZVu6PVzXIZH83glJfiqZU7gzxw9zSkinCNHZnJ0KViZmol/XUEvGPu0toWOnM5t9MUVRq3xMldo6TKOZ7tvqBDoYD/hMHSBZb+b5f12l7i43wV7dunypy+nKtlb+rv9YJdMdbVaXy29K5EPaQujYTZTvXFEB9b8P0NXt0jA+qsUEf6/TK7dONdh2PFrUFiLXtNxkw21n/q6JGfR78etQ3mIaDKffjoVYHKgMv2edGWpjAkZeM5eBg6U6kb7CMMstpxPfOPADkXu4hbWhMGG5TC4tuizfq8YAeE8t2nyfB+xq8MtQe5jTPLK1/B+NVuKvp+3WLDSrai6dbsMpFsZDXJL34BkoY7XsRf8FeaPiy5Z3ScD6YLTl986rztAPyLCKJrfPSSc2tAOgne9cGFVUPS+tehqtW+VPeD4qu00h7H9hX/x+hefqYL5cfS3h/qgpcUFw+69rVK6r1zcBwJyJAI9gUQ08628iirYku3KkUQ0VdlavrYYfB9wyStQ4VBUYpXKMhKgk5gCRRkEuJ2gETffj+nLZAqL13yFPm8lCOgRztp06S+K9Xq/cYVvAnDh8R2IsBGbs4KmpKMM7PA7mYf3XMI1KzAWXqc6RCv1a+PUwMK/AIKqnk040n2Q0yxuJSOufcVE6mWxVywHag9Ucww1FuSR54i7w=="
    }

Plan: 2 to add, 0 to change, 2 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```

**Comment by smorimoto** [comment] 2020-11-23 15:40
And pass "yes" to it. ​An error occurs.

**Comment by remyleone** [comment] 2021-09-02 13:42
@smorimoto could you retry? It should be fixed now.

**Closed** 2022-04-15 13:13 UTC
Labels: account
