### ISSUE TITLE
Impossible to add scaleway_instance_placement_group in a project different from default

### ISSUE THREAD

**Issue by warielon** [scaleway/terraform-provider-scaleway#806] opened 2021-03-31 13:40 UTC
### Terraform Version

Terraform v0.14.8
+ provider registry.terraform.io/carlpett/sops v0.5.3
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/scaleway/scaleway v2.0.0

### Affected Resource(s)

- scaleway_instance_placement_group when project_id different from default

### Terraform Configuration Files

```hcl
resource "scaleway_instance_placement_group" "place-fr-par-2" {
  project_id = "xxxxx" // with project_id different from default
  name = "place-fr-par-2"
  zone = "fr-par-2"
} 
```

### Expected Behavior

``` 
terraform plan
Terraform will perform the following actions:
 # scaleway_instance_placement_group.place-fr-par-2 will be created
  + resource "scaleway_instance_placement_group" "place-fr-par-2" {
      + id               = (known after apply)
      + name             = "place-fr-par-2"
      + organization_id  = (known after apply)
      + policy_mode      = "optional"
      + policy_respected = (known after apply)
      + policy_type      = "max_availability"
      + project_id       = "bb1480d4-dc19-4258-9dec-e3ac994b6483"
      + zone             = "fr-par-2"
    }
```

### Actual Behavior

Error: scaleway-sdk-go: http error 403 Forbidden: authorization required

### Important Factoids

I contacted Scaleway assistance and they told me it appears to be a bug directly in the Terraform provider.

It is working in project default.

Thanks :)

**Comment by Sh4d1** [comment] 2021-03-31 13:42
Hello 👋 do you use different credentials than from the default project?

**Comment by warielon** [comment] 2021-03-31 14:07
Hello,

I used a different project_id.
I have already been able to create ressources in this other project.

I have 2 providers for my 2 projects defined in my config.
````hcl
provider "scaleway" {
  alias      = "apollon1"
  access_key = data.sops_file.secrets["scaleway"].data["access_key_project_apollon"]
  secret_key = data.sops_file.secrets["scaleway"].data["secret_key_project_apollon"]
  project_id = "XXX"
  zone            = "fr-par-1"
  region          = "fr-par"
}

# project default
  provider "scaleway" {
  alias      = "default"
  access_key = data.sops_file.secrets["scaleway"].data["access_key_project_default"]
  secret_key = data.sops_file.secrets["scaleway"].data["secret_key_project_default"]
  project_id = "YYY"
  region          = "fr-par"
  zone            = "fr-par-1"
}
````

Thanks

**Comment by Sh4d1** [comment] 2021-03-31 14:28
> I have already been able to create ressources in this other project.

Via Terraform I suppose?

Weird though 🤔 could you run it with `TF_LOG=debug` and check to catch the 403 call?

**Comment by Sh4d1** [comment] 2021-03-31 15:11
Ah there is an issue with the debug logs, there should be the request body/response 🤔 anyway that's another issue 😓 (cc @remyleone )

Can you create a placement group in this project via the cli and the given credentials? I'll try to reproduce on my end

**Comment by Sh4d1** [comment] 2021-03-31 15:54
In this case you are using the same credentials right? The api keys are bound to a single project

**Comment by warielon** [comment] 2021-03-31 15:58
Indeed I have been able to create the placement group with the command line tool given the good project_id !

**Comment by Sh4d1** [comment] 2021-03-31 16:07
Weird I can't seem to reproduce. My guess it it's using the other key. Could you isolate a single provider and try to reproduce? 🤔

**Comment by Xaving** [comment] 2022-06-21 12:37
We face similar difficulties when creating bucket or instance. It's a more general problem concerning the alias in provider. This is described in the following issue #1337.
As a workaround, we did a change that is available in the terraform registry: [cryptobioz/scaleway](https://registry.terraform.io/providers/cryptobioz/scaleway/latest)
Pointing to the new provider as follow, should solve your problem.

```
required_providers {
    scaleway = {
      source = "cryptobioz/scaleway"
      version = "2.2.1-profiles"
    }
  }
```

**Comment by Codelax** [comment] 2022-08-29 09:16
Duplicate of #1337

**Closed by Codelax** 2022-08-29 09:16 UTC
Labels: bug, instance

**Comment by remyleone** [comment] 2022-08-29 09:56
@Xaving could you open a PR with this change so that we can have a conversation about it?
