### ISSUE TITLE
Terraform think that kubernetes certificate has changed

### ISSUE THREAD

**Issue by Nainterceptor** [scaleway/terraform-provider-scaleway#788] opened 2021-02-26 14:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
➜ terraform -v             
Terraform v0.14.7
+ provider registry.terraform.io/gitlabhq/gitlab v3.4.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/scaleway/scaleway v2.0.0-rc.2
```

### Affected Resource(s)

* scaleway_XXXX

### Terraform Configuration Files

https://gitlab.com/test-gitlab14/test-scaleway-gitlab

### Debug Output

With Trace level : https://gitlab.com/test-gitlab14/test-scaleway-gitlab/-/jobs/1058831304

### Expected Behavior

Certificate in kubeconfig has no changes, so terraform should not update the certificate in gitlab resource

### Actual Behavior

Terraform think that certificate has changed, and trigger un update in gitlab resource.

### Steps to Reproduce

Apply this two times : 
https://gitlab.com/test-gitlab14/test-scaleway-gitlab

### Important Factoids

No

**Comment by remyleone** [comment] 2021-02-26 16:28
I was not able to reproduce with only scaleway resources. The terraform files are accepted and are running normally. Could you trim the sources provided and only involve the Scaleway provider?

**Comment by Sh4d1** [comment] 2021-02-27 11:53
Maybe it's the null_resource ? 🤔

**Comment by remyleone** [comment] 2021-04-27 12:21
No answers for more than one month, I'm closing it. @Nainterceptor do not hesitate to open a new issue with steps to reproduce the issue :)

**Closed by remyleone** 2021-04-27 12:21 UTC
Labels: k8s

**Comment by Nainterceptor** [comment] 2021-08-30 22:27
Just checked, seems to be related to issue in gitlab provider. Thanks.
